name: amanah_ui
description: "Amanah-Bot EaaS Portal"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  http_parser: ^4.0.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
